pool:
  vmImage: 'ubuntu-16.04'
variables:
    registryEndpoint: 
steps: 
- script: docker login -u $(dockerId) -p $(pswd) transacoesfinanceiras:$(build.buildId)
- task: DockerCompose@0
  displayName: Compose build back_transacoesfinanceiras
  inputs:
    dockerComposeCommand: 'build magva.back.transacoesfinanceiras'
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: $(registryEndpoint)
    dockerComposeFile: docker-compose.yml
    qualifyImageNames: true
    projectName: ""
    dockerComposeFileArgs: |
      TAG=$(Build.SourceBranchName)
- task: DockerCompose@0
  displayName: Compose push back_transacoesfinanceiras
  inputs:
    dockerComposeCommand: 'push magva.back.transacoesfinanceiras'
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: $(registryEndpoint)
    dockerComposeFile: docker-compose.yml
    qualifyImageNames: true
    projectName: ""
    dockerComposeFileArgs: |
      TAG=$(Build.SourceBranchName)