pool:
  vmImage: 'ubuntu-16.04'
steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    includeLatestTag: true