// <auto-generated />
using MAGVA.Back.TransacoesFinanceiras.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAGVA.Back.TransacoesFinanceiras.Infrastructure.DataBase.Migrations.TransacoesFinanceiras
{
    [DbContext(typeof(TransacoesFinanceirasContext))]
    [Migration("20190530084452_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:TransacoesFinanceiras.consumidorseq", $"'consumidorseq', 'TransacoesFinanceiras', '{int.MinValue}', '1', '{int.MaxValue}', '{int.MinValue}', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAGVA.Back.TransacoesFinanceiras.Domain.AggregatesModel.ConsumidorAggregate.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "consumidorseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "TransacoesFinanceiras")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Email");

                    b.Property<int>("LoginId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("Consumidor","TransacoesFinanceiras");
                });
#pragma warning restore 612, 618
        }
    }
}
