// <auto-generated />
using MAGVA.Back.TransacoesFinanceiras.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

namespace MAGVA.Back.TransacoesFinanceiras.Infrastructure.DataBase.Migrations.TransacoesFinanceiras
{
    [DbContext(typeof(TransacoesFinanceirasContext))]
    partial class TransacoesFinanceirasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:TransacoesFinanceiras.consumidorseq", "'consumidorseq', 'TransacoesFinanceiras', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAGVA.Back.TransacoesFinanceiras.Domain.AggregatesModel.ConsumidorAggregate.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "consumidorseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "TransacoesFinanceiras")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Email");

                    b.Property<int>("LoginId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("Consumidor","TransacoesFinanceiras");
                });

            modelBuilder.Entity("MAGVA.Back.TransacoesFinanceiras.Infrastructure.Idempotency.ClientRequest", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name")
                    .IsRequired();

                b.Property<DateTime>("Time");

                b.HasKey("Id");

                b.ToTable("Requests", "Sistema");
            });
#pragma warning restore 612, 618
        }
    }
}
